prefcomp watches Library/Containers now

diff --git a/utils/prefcomp b/utils/prefcomp
--- a/utils/prefcomp
+++ b/utils/prefcomp
@@ -4,9 +4,14 @@
 # afterwards.  Used to figure out what preferences are changed when
 # you click things in the GUI.
 
-set -euo pipefail
+set -uo pipefail
 
-PRINT_PLIST=$HOME/Downloads/printplist.py
+PREFS_DIRS=(
+	~/Library/Preferences
+	~/Library/Containers
+	~/Library/Group\ Containers
+)
+PRINT_PLIST="$(dirname "$0")"/printplist.py
 
 temp_dir=$(mktemp -d)
 rm_temp_dir() {
@@ -22,10 +27,14 @@ com.apple.homed.plist
 com.apple.homed.notbackedup.plist
 EOF
 
-rsync -a --exclude-from="$excludes" ~/Library/Preferences "$temp_dir"/
+rsync -a --exclude-from="$excludes" "${PREFS_DIRS[@]}"  "$temp_dir"/
+if [[ $? != 0 && $? != 23 ]]; then
+	echo "rsync failed, exiting" >&2
+	exit 1
+fi
 echo "Watching, kill to compare"
 change_log=$temp_dir/changed
-! fswatch -r ~/Library/Preferences -E --exclude '\.plist.[a-zA-Z0-9]+$' \
+fswatch -r "${PREFS_DIRS[@]}" -E --exclude '\.plist.[a-zA-Z0-9]+$' \
 	| tee "$change_log"
 while read -r file; do
 	echo
@@ -38,6 +47,6 @@ while read -r file; do
 		cat "$temp_dir/after"
 	else
 		"$PRINT_PLIST" "$old_file" > "$temp_dir/before"
-		! colordiff -y -W 200 "$temp_dir/before" "$temp_dir/after"
+		colordiff -y -W 200 "$temp_dir/before" "$temp_dir/after"
 	fi
 done < <(sort -u "$change_log")
